CREATE TABLE Schools (
    id SERIAL PRIMARY KEY,           -- Auto-incrementing primary key
    name VARCHAR(255) NOT NULL,      -- Name of the school
    location VARCHAR(255) NOT NULL,  -- Location of the school
    website VARCHAR(255) NOT NULL,   -- Website of the school
    school_type VARCHAR(50),         -- Type of school (e.g., University, College)
    has_scholarship BOOLEAN          -- Whether the school offers scholarships
);

-- Insert values into the Schools table
INSERT INTO Schools (name, location, website, school_type, has_scholarship)
VALUES(('The University of Akron', 'Akron Esports', 'Akron, Ohio', 'https://www.uakron.edu/esports/', TRUE),
('Albright College', 'Albright College Esports', 'Reading, Pennsylvania', NULL, TRUE),
('Alfred State College', 'Alfred State Esports', 'Alfred, New York', 'https://www.alfredstate.edu/athletics/esports/',TRUE),
('Alvernia University', 'Alvernia University Esports', 'Reading, Pennsylvania', 'https://www.alvernia.edu/esports',TRUE),
('Anna Maria College', 'Anna Maria Esports', 'Paxton, Massachusetts', 'https://www.annamaria.edu/esports/',TRUE),
('Aquinas College', 'Aquinas College Esports', 'Grand Rapids, Michigan', 'https://www.aquinas.edu/athletics/esports/',TRUE),
('Arcadia University', 'Arcadia Esports', 'Glenside, Pennsylvania', 'https://www.arcadia.edu/clubs/esports/',TRUE),
('Ashland University', 'Ashland Esports', 'Ashland, Ohio', 'https://www.ashland.edu/athletics/esports/',TRUE),
('Anderson University', 'AU Esports', 'Anderson, Indiana', 'https://www.anderson.edu/esports/',TRUE),
('Baker College', 'Baker College Esports', 'Royal Oak, Michigan', 'https://www.bakercoll.edu/esports/',TRUE),
('Ball State University', 'Ball State Esports', 'Muncie, Indiana', 'https://www.bsu.edu/esports/',TRUE),
('Barry University', 'Barry University Esports', 'Miami Shores, Florida', 'https://www.barry.edu/esports/',TRUE),
('Bushnell University', 'Beacons', 'Eugene, Oregon', NULL,TRUE),
('Maryville University', 'Bearcat Esports', 'Maryville, Missouri', NULL,TRUE),
('Buena Vista University', 'Beaver Esports', 'Storm Lake, Iowa', NULL,TRUE),
('Bethany College', 'Bethany College Esports', 'Bethany, West Virginia', 'https://www.bethanywv.edu/esports',TRUE),
('Bowling Green State University', 'BGSU Esports', 'Bowling Green, Ohio', 'https://www.bgsu.edu/esports/', TRUE),
('Worcester State University', 'Blue and White Esports', 'Worcester, Massachusetts', NULL,TRUE),
('Salisbury University', 'Blue Bears', 'Salisbury, North Carolina', 'https://www.salisbury.edu/clubs/esports/',TRUE),
('Presbyterian College', 'Blue Hose Esports', 'Clinton, South Carolina', NULL,TRUE),
('Illinois College', 'Blueboys', 'Jacksonville, Illinois', NULL,TRUE),
('Bryant and Stratton College-Winsconsin', 'Bobcats Esports', 'Wauwatosa, Wisconsin', NULL,TRUE),
('Boise State University', 'Boise State Esports', 'Boise, Idaho', 'https://www.boisestate.edu/esports/',TRUE),
('Brescia University', 'Brescia Esports', 'Owensboro, Kentucky', 'https://www.brescia.edu/esports/',TRUE),
('Brewton-Parker College', 'Brewton-Parker Esports', 'Mount Vernon, Georgia', 'https://www.bpc.edu/esports/',TRUE),
('Carolina University', 'Bruins', 'Winston-Salem, North Carolina', NULL,TRUE),
('Bryant & Stratton College', 'Bryant & Stratton Esports', 'Syracuse, New York', 'https://www.bryantstratton.edu/esports/',TRUE),
('Bryant & Stratton College-virginia', 'BSC Bobcats VA', 'Virginia Beach, Virginia', NULL,TRUE),
('Baker University', 'BU Esports', 'Baldwin City, Kansas', 'https://www.bakeru.edu/esports/',TRUE),
('Campbellsville University', 'Campbellsville University Esports', 'Campbellsville, Kentucky', 'https://www.campbellsville.edu/esports/',TRUE),
('Carthage College', 'Carthage Firebirds', 'Kenosha, Wisconsin', 'https://www.carthage.edu/esports/',TRUE),
('Catawba College', 'Catawba Esports', 'Salisbury, North Carolina', 'https://www.catawba.edu/esports/',TRUE),
('Catawba Valley Community College', 'Catawba Valley Red Hawk Esports', 'Hickory, NC', 'https://www.cvc.edu/esports/',TRUE),
('WVU Potomac State College', 'Catamount Esports', 'Keyser, WV', NULL,TRUE),
('University of St Thomas', 'Celts', 'Houston, TX', NULL,TRUE),
('Central Michigan University', 'Central Michigan Esports', 'Mount Pleasant, MI', 'https://www.cmich.edu/esports/',TRUE),
('Briar Cliff University', 'Chargers', 'Sioux City, IA', NULL,TRUE),
('Capitol Technology University', 'Chargers', 'South Laurel, MD', NULL,TRUE),
('University of New Haven', 'Chargers', 'West Haven, CT', 'https://www.newhaven.edu/esports/',TRUE),
('Columbia International University', 'CIU Rams Esports', 'Columbia, SC', 'https://www.ciu.edu/esports/',TRUE),
('Clark University', 'Clark Esports', 'Worcester, MA', 'https://www.clarku.edu/esports/',TRUE),
('Clarke University', 'Clarke Esports', 'Dubuque, IA', 'https://www.clarke.edu/esports/',TRUE),
('Cleveland State University', 'Cleveland State Esports', 'Cleveland, OH', 'https://www.csuohio.edu/esports/',TRUE),
('Cleary College', 'Cleary Cougars Esports', 'Howell, MI', 'https://www.cleary.edu/esports/',TRUE),
('Coastal Bend College', 'Coastal Bend Esports', 'Beeville, TX', 'https://www.coastalbend.edu/esports/',TRUE),
('Coker University', 'Coker University Esports', 'Hartsville, SC', 'https://www.coker.edu/esports/',TRUE),
('Columbia College', 'Columbia College Esports', 'Columbia, MO', 'https://www.columbiacollege.edu/esports/',TRUE),
('Western Iowa Tech Communiy College', 'Comets', 'Sioux City, IA', NULL,TRUE),
('Concord University', 'Concord Esports', 'Athens, WV', 'https://www.concord.edu/esports/',TRUE),
('Concordia University, St. Paul', 'Concordia University - St. Paul Esports', 'St. Paul, MN', 'https://www.csp.edu/esports/',TRUE),
('Concordia University Ann Arbor', 'Concordia University Ann Arbor Esports', 'Ann Arbor, MI', NULL,TRUE),
('Concordia University Texas', 'ConcordiaTX Esports', 'Austin, TX', 'https://www.concordia-tx.edu/esports/',TRUE),
('Converse College', 'Converse Esports', 'Spartanburg, SC', 'https://www.converse.edu/esports/',TRUE),
('Cornell College', 'Cornell Esports', 'Mount Vernon, IA', 'https://www.cornellcollege.edu/esports/',TRUE),
('Cottey College', 'Cottey College Esports', 'Nevada, MO', 'https://www.cottey.edu/esports/',TRUE),
('Caldwell University', 'Cougar Esports', 'Caldwell, NJ', 'https://www.caldwell.edu/esports/',TRUE),
('Averett University', 'Cougars', 'Danville, VA', NULL,TRUE),
('CUNE', 'CUNE Esports', 'Seward, NE', 'https://www.cune.edu/esports/',TRUE),
('Cumberland University', 'Cumberland University Esports', 'Lebanon, TN', 'https://www.cumberland.edu/esports/',TRUE),
('Dallas Baptist University', 'Dallas Baptist University Esports', 'Dallas, TX', 'https://www.dbu.edu/esports/',TRUE),
('Davenport University', 'Davenport Esports', 'Grand Rapids, MI', 'https://www.davenport.edu/esports/',TRUE),
('DePaul University', 'DePaul University Esports', 'Chicago, IL', 'https://www.depaul.edu/esports/',TRUE),
('Dickinson State University', 'DSU Esports', 'Dickinson, ND', 'https://www.dsu.edu/esports/',TRUE),
('The University of North America', 'Dragons Esports', 'Fairfax, VA', NULL,TRUE),
('Wake Technical Community College', 'Eagles', 'Raleigh, NC', NULL,TRUE),
('Edgewood College', 'Edgewood College Esports', 'Madison, WI', 'https://www.edgewood.edu/esports/',TRUE),
('Elmhurst University', 'Elmhurst University Esports', 'Elmhurst, IL', 'https://www.elmhurst.edu/esports/',TRUE),
('Vila Maria College', 'Esport', 'Buffalo, NY', NULL,TRUE),
('Virginia Wesleyan University', 'Esports', 'Virginia Beach, VA', NULL,TRUE),
('Eastern Wyoming College', 'EWC Esports', 'Torrington, WY', 'https://www.ewc.edu/esports/',TRUE),
('Lackawanna College', 'Falcons', 'Scranton, PA', NULL,TRUE),
('Ferris State University', 'Ferris Esports', 'Big Rapids, MI', 'https://www.ferris.edu/esports/',TRUE),
('University of St Francis', 'Fighting Saints Esports', 'Joliet, IL', NULL,TRUE),
('Fisher College', 'Fisher Esports', 'Boston, MA', 'https://www.fisher.edu/esports/',TRUE),
('Florida Southern College', 'Florida Southern College Esports', 'Lakeland, FL', 'https://www.floridasouthern.edu/esports/',TRUE),
('Florida Institute of Technology', 'Florida Tech Esports', 'Melbourne, FL', 'https://www.fit.edu/esports/',TRUE),
('Florida National University', 'FNU Esports', 'Hialeah, FL', 'https://www.fnu.edu/esports/',TRUE),
('Fresno Pacific University', 'FPU Esports', 'Fresno, CA', 'https://www.fresnopacific.edu/esports/',TRUE),
('Garden City Community College', 'GC esports', 'Garden City, KS', 'https://www.gcc.edu/esports/',TRUE),
('Grand Canyon University', 'GCU Esports', 'Phoenix, AZ', 'https://www.gcu.edu/esports/',TRUE),
('George Fox University', 'GFU Esports', 'Newberg, OR', 'https://www.georgefox.edu/esports/',TRUE),
('Grays Harbor College', 'GHC Esports', 'Aberdeen, WA', 'https://www.ghc.edu/esports/',TRUE),
('Gogebic Community College', 'Gogebic Samsons Esports', 'Ironwood, MI', NULL,TRUE),
('Graceland University', 'Graceland Esports', 'Lamoni, IA', 'https://www.graceland.edu/esports/',TRUE),
('Grwn Universityand View University', 'Grand View University Esports', 'Des Moines, IA', 'https://www.grandview.edu/esports/',TRUE),
('Greenville University', 'Greenville University Panthers', 'Greenville, IL', 'https://www.greenville.edu/esports/',TRUE),
('Missouri Western State University', 'Griffon Esports', 'St. Joseph, MO', NULL,TRUE),
('Governors State University', 'GSU Esports', 'University Park, IL', 'https://www.govst.edu/esports/',TRUE),
('Northwestern Michigan College', 'Hawk Owls Esports', 'Traverse City, MI', NULL,TRUE),
('Heidelberg University', 'Heidelberg Esports', 'Tiffin, OH', 'https://www.heidelberg.edu/esports/',TRUE),
('Hendrix College', 'Hendrix Esports', 'Conway, AR', 'https://www.hendrix.edu/esports/',TRUE),
('Harrisburg University', 'HU Storm', 'Harrisburg, PA', 'https://www.harrisburgu.edu/esports/',TRUE),
('Huntingdon College', 'Huntingdon Esports', 'Montgomery, AL', 'https://www.huntingdon.edu/esports/',TRUE),
('Huntington University', 'Huntington Esports', 'Huntington, IN', 'https://www.huntington.edu/esports/',TRUE),
('St. Cloud State University', 'Huskies Esports', 'St. Cloud, MN', 'https://www.stcloudstate.edu/esports/',TRUE),
('Louisburg College', 'Hurricane Esports', 'Louisburg, NC', 'https://www.louisburg.edu/esports/',TRUE),
('Independence Community College', 'ICC Pirate Esports', 'Independence, KS', 'https://www.iccks.edu/esports/',TRUE),
('Illinois Institute of Technology', 'Illinois Tech Esports', 'Chicago, IL', 'https://www.iit.edu/esports/',TRUE),
('Illinois Wesleyan University', 'Illinois Wesleyan University Esports', 'Bloomington, IL', 'https://www.iwu.edu/esports/',TRUE),
('Indiana Institute of Technology', 'Indiana Tech Esports', 'Fort Wayne, IN', 'https://www.indianatech.edu/esports/',TRUE),
('Indiana University Kokomo', 'IUK Esports', 'Kokomo, IN', 'https://www.iuk.edu/esports/',TRUE),
('Indiana University East', 'IUE Red Wolves Esports', 'Richmond, IN', 'https://www.iue.edu/esports/',TRUE),
('John Brown University', 'JBU Esports', 'Siloam Springs, AR', 'https://www.jbu.edu/esports/',TRUE),
('Walter Starling', 'JCC Jaguar eSports', 'Smithfield, NC', NULL,TRUE),
('Jewell College', 'Jewell Esports', 'Liberty, MO', 'https://www.jewell.edu/esports/',TRUE),
('John Wood Community College', 'JWCC Esports', 'Quincy, IL', 'https://www.jwcc.edu/esports/',TRUE),
('Kansas Wesleyan University', 'Kansas Wesleyan Coyotes', 'Salina, KS', 'https://www.kwu.edu/esports/',TRUE),
('Keene State College', 'Keene State Esports', 'Keene, NH', 'https://www.keene.edu/esports/',TRUE),
('Keiser University', 'Keiser University Jacksonville Esports', 'Jacksonville, FL', 'https://www.keiseruniversity.edu/esports/',TRUE),
('Keiser University', 'Keiser University Lakeland Esports', 'Lakeland, FL', 'https://www.keiseruniversity.edu/esports/',TRUE),
('Kettering University', 'Kettering University Esports', 'Flint, MI', 'https://www.kettering.edu/esports/',TRUE),
('Keyano College', 'Keyano Huskies Esports', 'Fort McMurray, Canada', 'https://www.keyano.ca/esports/',TRUE),
('King University', 'King University Esports', 'Bristol, TN', 'https://www.king.edu/esports/',TRUE),
('Bellarmine University', 'Knights Esports', 'Louisville, KY', 'https://www.bellarmine.edu/esports/',TRUE),
('Keiser University Flagship', 'KU Flagship', 'West Palm Beach, FL', NULL,TRUE),
('Keiser University Pembroke Pines', 'KUPP Esports', 'Pembroke Pines, FL', NULL,TRUE),
('Lakeland University', 'Lakeland Esports', 'Sheboygan, WI', 'https://www.lakeland.edu/esports/',TRUE),
('Hesston College', 'Larks Esports', 'Hesston, KS', 'https://www.hesston.edu/esports/',TRUE),
('Lawrence Technological University', 'Lawrence Tech Esports', 'Southfield, MI', 'https://www.ltu.edu/esports/',TRUE),
('Lees-McRae College', 'Lees-McRae College Esports', 'Banner Elk, NC', 'https://www.leesmcrae.edu/esports/',TRUE),
('Limestone University', 'Limestone Esports', 'Gaffney, SC', 'https://www.limestone.edu/esports/',TRUE),
('Freed-Hardeman University', 'Lions', 'Henderson, TN', NULL,TRUE),
('Lincoln Land Community College', 'Loggers', 'Springfield, IL', 'https://www.lincolnland.edu/esports/',TRUE),
('Lourdes University', 'Lourdes Esports', 'Sylvania, OH', 'https://www.lourdes.edu/esports/',TRUE),
('Loyola University New Orleans', 'Loyno Esports', 'New Orleans, LA', 'https://www.loyno.edu/esports/',TRUE),
('Lehigh Valley College', 'LVC Esports', 'Annville, PA', 'https://www.lvc.edu/esports/',TRUE),
('Lesley University', 'Lynx', 'Cambridge, MA', NULL,TRUE),
('Mid-America Christian University', 'MACU Esports', 'Oklahoma City, OK', 'https://www.macu.edu/esports/',TRUE),
('Moberly Area Community College', 'MACC Greyhound Esports', 'Moberly, MO', 'https://www.macc.edu/esports/',TRUE),
('Malone University', 'Malone Pioneers Esports', 'Canton, OH', 'https://www.malone.edu/esports/',TRUE),
('Manchester University', 'Manchester Esports', 'North Manchester, IN', 'https://www.manchester.edu/esports/',TRUE),
('Marietta College', 'Marietta College Esports', 'Marietta, OH', 'https://www.marietta.edu/esports/',TRUE),
('Mars Hill University', 'Mars Hill Esports', 'Mars Hill, NC', 'https://www.marshill.edu/esports/',TRUE),
('Marshalltown Community College', 'Marshalltown Community College Tigers Esports', 'Marshalltown, IA', 'https://www.marshalltowncc.edu/esports/',TRUE),
('Minnesota State University, Mankato', 'Mavericks Esports', 'Mankato, MN', 'https://www.mnsu.edu/esports/',TRUE),
('McMurry University', 'McMurry Esports', 'Abilene, TX', 'https://www.mcm.edu/esports/',TRUE),
('Mercyhurst University', 'Mercyhurst Esports', 'Erie, PA', 'https://www.mercyhurst.edu/esports/',TRUE),
('Michigan State University', 'Michigan State University Esports', 'East Lansing, MI', NULL,TRUE),
('Michigan Technological University', 'Michigan Tech Esports', 'Houghton, MI', 'https://www.mtu.edu/esports/',TRUE),
('Midland University', 'Midland Esports', 'Fremont, NE', 'https://www.midland.edu/esports/',TRUE),
('Milligan University', 'Milligan University Esports', 'Milligan, TN', 'https://www.milligan.edu/esports/',TRUE),
('New College of Florida', 'Mighty Banyans', 'Sarasota, FL', NULL,TRUE),
('Oakland City University', 'Mighty Oaks', 'Oakland City, IN', 'https://www.oca.edu/esports/',TRUE),
('Minnesota State University Moorhead', 'MSUM Esports', 'Moorhead, MN', 'https://www.msum.edu/esports/',TRUE),
('University of Missouri', 'Mizzou Esports', 'Columbia, MO', 'https://www.mizzou.edu/esports/',TRUE),
('Molloy College', 'Molloy Esports', 'Rockville Centre, NY', 'https://www.molloy.edu/esports/',TRUE),
('Mount St. Mary''s University', 'Mount Esports', 'Emmitsburg, MD', 'https://www.msmary.edu/esports/',TRUE),
('University of Mount Union', 'Mount Union Esports', 'Alliance, OH', 'https://www.mountunion.edu/esports/',TRUE),
('Missouri Valley College', 'MOVAL', 'Marshall, MO', NULL,TRUE),
('Muskingum University', 'Muskingum Esports', 'New Concord, OH', 'https://www.muskingum.edu/esports/',TRUE),
('Navarro College', 'Navarro College Esports', 'Corsicana, TX', 'https://www.navarrocollege.edu/esports/',TRUE),
('North Central University', 'NCU Esports', 'Minneapolis, MN', NULL,TRUE),
('Northeastern Oklahoma A&M college', 'NEO Esports', 'Miami, OK', NULL,TRUE),
('New England Institute of Technology', 'New England Tech Tigers', 'East Greenwich, RI', 'https://www.neti.edu/esports/',TRUE),
('Newberry College', 'Newberry College Esports', 'Newberry, SC', 'https://www.newberry.edu/esports/',TRUE),
('Newman University', 'Newman Jets', 'Wichita, KS', 'https://www.newman.edu/esports/',TRUE),
('Nichols College', 'Nichols eSports', 'Dudley, MA', 'https://www.nichols.edu/esports/',TRUE),
('Northeast Iowa Community College', 'NICC Cougar Esports', 'Peosta, IA', 'https://www.niacc.edu/esports/',TRUE),
('University of North Alabama', 'North Alabama Esports', 'Florence, AL', 'https://www.una.edu/esports/',TRUE),
('Northwestern College ', 'Northwestern College Esports', 'Orange City, IA', NULL,TRUE),
('North Park University', 'NPU Esports', 'Chicago, IL', 'https://www.northpark.edu/esports/',TRUE),
('Northwest Oklahoma State University', 'NWOSU Esports', 'Alva, OK', 'https://www.nwosu.edu/esports/',TRUE),
('Oakland University', 'Oakland Esports', 'Rochester, MI', 'https://www.oakland.edu/esports/',TRUE),
('Oklahoma Christian University', 'Oklahoma Christian Esports', 'Edmond, OK', 'https://www.okcu.edu/esports/',TRUE),
('University of Oklahoma', 'Oklahoma Esports', 'Norman, OK', 'https://www.ou.edu/esports/',TRUE),
('Oklahoma Wesleyan University', 'OKWU Esports', 'Bartlesville, OK', 'https://www.okwu.edu/esports/',TRUE),
('Otterbein University', 'Otterbein Esports', 'Westerville, OH', 'https://www.otterbein.edu/esports/',TRUE),
('Ottawa university Arizona', 'OUAZ Esports', 'Surprise, AZ', NULL,TRUE),
('Pace University', 'Pace Esports', 'New York, NY', 'https://www.pace.edu/esports/',TRUE),
('University of South Carolina Aiken', 'Pacers Esports', 'Aiken, SC', 'https://www.usciken.edu/esports/',TRUE),
('Park University Gilbert', 'Park G Esports', 'Gilbert, AZ', NULL,TRUE),
('Francis Marion University', 'Patriots', 'Florence, SC', NULL,TRUE),
('Peninsula College', 'Peninsula College Esports', 'Port Angeles, WA', 'https://www.peninsulacollege.edu/esports/',TRUE),
('Cameron University', 'Pickaxes Esports', 'Lawton, OK', NULL,TRUE),
('Post University', 'Post University Esports', 'Waterbury, CT', 'https://www.post.edu/esports/',TRUE),
('Purdue University Northwest', 'Purdue University Northwest Esports', 'Hammond, IN', 'https://www.pnw.edu/esports/',TRUE),
('Putnam Science Academy', 'Putnam Science Academy Esports', 'Putnam, CT', NULL,TRUE),
('Radford University', 'Radford Esports', 'Radford, VA', 'https://www.radford.edu/esports/',TRUE),
('Ranger College', 'Ranger College Esports', 'Ranger, TX', 'https://www.rangercollege.edu/esports/',TRUE),
('Rochester College', 'RCU Esports', 'Rochester Hills, MI', 'https://www.rcu.edu/esports/',TRUE),
('Ripon College', 'Red Hawks Esports', 'Ripon, WI', 'https://www.ripon.edu/esports/',TRUE),
('Illinois State University', 'Redbird Esports', 'Normal, IL', 'https://www.illinoisstate.edu/esports/',TRUE),
('University of Rio Grande', 'Redstorm Esports', 'Rio Grande, OH', NULL,TRUE),
('Hawkeye Community College', 'RedTails Esports', 'Waterloo, IA', NULL,TRUE),
('Rockford University', 'Regents Esports', 'Rockford, IL', 'https://www.rockford.edu/esports/',TRUE),
('Iowa Western Community', 'Reiver Esports', 'Council Bluffs, IA', NULL,TRUE),
('Ringling College', 'Ringling Rollers', 'Sarasota, FL', 'https://www.ringling.edu/esports/',TRUE),
('Robert Morris University', 'RMU Esports', 'Moon Township, PA', 'https://www.rmu.edu/esports/',TRUE),
('Warner University', 'Royals', 'Lake Wales, FL', NULL,TRUE),
('Rogers State University', 'RSU Esports', 'Claremore, OK', 'https://www.rsu.edu/esports/',TRUE),
('Marian University', 'Sabres', 'Fond Du Lac, WI', NULL,TRUE),
('Russel Sage College', 'Sage eSports', 'Troy, NY', NULL,TRUE),
('Saint Xavier University', 'Saint Xavier Esports', 'Chicago, IL', 'https://www.sxu.edu/esports/',TRUE),
('Samford University', 'Samford Esports', 'Birmingham, AL', 'https://www.samford.edu/esports/',TRUE),
('Savannah College of Art and Design', 'SCAD Esports', 'Savannah, GA', 'https://www.scad.edu/esports/',TRUE),
('Keiser University Port Richey', 'Seahawks', 'New Port Richey, FL', NULL,TRUE),
('Keiser University', 'Seahawks Esports', 'Sarasota, FL', NULL,TRUE),
('Seton Hall University', 'Seton Hall Pirates Esports', 'South Orange, NJ', 'https://www.shupirates.com/esports/',TRUE),
('Siena Heights University', 'Siena Heights Esports', 'Adrian, MI', 'https://www.sienaheights.edu/esports/',TRUE),
('Simpson College', 'Simpson Esports', 'Indianola, IA', 'https://www.simpson.edu/esports/',TRUE),
('Southwest Minnesota State University', 'SMSUEsports', 'Marshall, MN', NULL,TRUE),
('University of Southern Mississippi', 'Southern Miss Esports', 'Hattiesburg, MS', 'https://www.usm.edu/esports/',TRUE),
('Southern Nazarene University', 'Southern Nazarene Esports', 'Bethany, OK', 'https://www.snu.edu/esports/',TRUE),
('University of St. Mary', 'Spires Esports', 'Leavenworth, KS', NULL,TRUE),
('St. Ambrose University', 'St. Ambrose Fighting Bees Esports', 'Davenport, IA', 'https://www.stambrose.edu/esports/',TRUE),
('St. Andrews University', 'St. Andrews University Esports', 'Laurinburg, NC', 'https://www.standrews.edu/esports/',TRUE),
('St. Bonaventure University', 'St. Bonaventure Varsity Esports', 'St. Bonaventure, NY', 'https://www.sbu.edu/esports/',TRUE),
('St. Clair College', 'St. Clair Saints', 'Windsor, Canada', 'https://www.stclaircollege.ca/esports/',TRUE),
('St. Edward''s University', 'St. Edward''s University Esports', 'Austin, TX', 'https://www.stedwards.edu/esports/',TRUE),
('St. Lawrence University', 'St. Lawrence University Esports', 'Canton, NY', 'https://www.stlawu.edu/esports/',TRUE),
('St. Mary''s University', 'St. Mary''s Esports', 'San Antonio, TX', 'https://www.stmarytx.edu/esports/',TRUE),
('Stevenson University', 'Stevenson Esports', 'Owings Mills, MD', 'https://www.stevenson.edu/esports/',TRUE),
('Bethany College', 'Swedes Esports', 'Lindsborg, KS', NULL,TRUE),
('Southwestern Illinois College', 'SWIC Bluestorm', 'Belleville, IL', 'https://www.swic.edu/esports/',TRUE),
('Southwestern Oklahoma State University', 'SWOSU Esports', 'Weatherford, OK', 'https://www.swosu.edu/esports/',TRUE),
('Syracuse University', 'Syracuse Esports', 'Syracuse, NY', 'https://www.syracuse.edu/esports/',TRUE),
('Texas A&M University–Texarkana', 'TAMUT Eagle Esports', 'Texarkana, TX', 'https://www.tamut.edu/esports/',TRUE),
('Texas A&M University–San Antonio', 'TAMUSA Esports', 'San Antonio, TX', 'https://www.tamusa.edu/esports/',TRUE),
('Thomas College', 'Thomas Esports', 'Waterville, ME', 'https://www.thomas.edu/esports/',TRUE),
('Thomas More College', 'Thomas More Esports', 'Crestview Hills, KY', 'https://www.thomasmore.edu/esports/',TRUE),
('Central Christian College', 'Tigers Esports', 'McPherson, KS', 'https://www.mcpherson.edu/esports/',TRUE),
('Dakota Wesleyan University', 'Tigers Esports', 'Mitchell, SD', NULL,TRUE),
('Tiffin University', 'Tiffin Esports', 'Tiffin, OH', 'https://www.tiffin.edu/esports/',TRUE),
('Truett McConnel University', 'TMU Esports', 'Cleveland, GA', NULL,TRUE),
('Transylvania University', 'Transy Esports', 'Lexington, KY', 'https://www.transy.edu/esports/',TRUE),
('Trine University', 'Trine Esports', 'Angola, IN', 'https://www.trine.edu/esports/',TRUE),
('Troy University', 'Troy Trojan Gaming', 'Troy, AL', 'https://www.troy.edu/esports/',TRUE),
('University of the Cumberlands', 'UC Esports', 'Williamsburg, KY', 'https://www.ucumberlands.edu/esports/',TRUE),
('UNC Asheville', 'UNC Asheville Bulldogs Esports', 'Asheville, NC', 'https://www.unca.edu/esports/',TRUE),
('University of Montevallo', 'UM Esports', 'Montevallo, AL', 'https://www.montevallo.edu/esports/',TRUE),
('University of Michigan–Flint', 'UM-Flint Esports', 'Flint, MI', 'https://www.umflint.edu/esports/',TRUE),
('University of Jamestown', 'University of Jamestown Esports', 'Jamestown, ND', 'https://www.uj.edu/esports/',TRUE),
('University of Mount Saint Vincent', 'UMSV Esports', 'Bronx, NY', 'https://www.mountsaintvincent.edu/esports/',TRUE),
('University of North Texas', 'UNT Esports', 'Denton, TX', 'https://www.unt.edu/esports/',TRUE),
('University of Pikeville', 'UPIKE Esports', 'Pikeville, KY', 'https://www.upike.edu/esports/',TRUE),
('University of South Caroline Sumter', 'USC Sumter Fire Ants Esports', 'Sumter, SC', 'https://www.uscsumter.edu/esports/',TRUE),
('University of Saint Francis', 'USF Esports', 'Fort Wayne, IN', NULL,TRUE),
('University of Saint Katherine', 'USK Firebirds Esports', 'San Marcos, CA', NULL,TRUE),
('Utica University', 'Utica University Esports', 'Utica, NY', 'https://www.utica.edu/esports/',TRUE),
('University of Tennessee at Chattanooga', 'UTC Esports', 'Chattanooga, TN', 'https://www.utc.edu/esports/',TRUE),
('Augustana College', 'Viking Esports', 'Rock Island, IL', NULL,TRUE),
('Viterbo University', 'Viterbo Esports', 'La Crosse, WI', 'https://www.viterbo.edu/esports/',TRUE),
('Wagner College', 'Wagner E-Hawks', 'Staten Island, NY', 'https://www.wagner.edu/esports/',TRUE),
('Waubonsee Community College', 'Waubonsee Chiefs', 'Sugar Grove, IL', 'https://www.waubonsee.edu/esports/',TRUE),
('Webber International University', 'Webber Esports', 'Babson Park, FL', 'https://www.webber.edu/esports/',TRUE),
('University of Arkansas at Monticello', 'Weevil Esports', 'Monticello, AR', 'https://www.uam.edu/esports/',TRUE),
('West Virginia Wesleyan College', 'West Virginia Wesleyan College Esports', 'Buckhannon, WV', 'https://www.wvwc.edu/esports/',TRUE),
('Wichita State University', 'Wichita State Esports', 'Wichita, KS', 'https://www.wichita.edu/esports/',TRUE),
('Indiana Wesleyan University', 'Wildcats', 'Marion, IN', NULL,TRUE),
('Winthrop University', 'Winthrop Esports', 'Rock Hill, SC', 'https://www.winthrop.edu/esports/',TRUE),
('Wisconsin Lutheran College', 'Wisconsin Lutheran College Esports', 'Milwaukee, WI', 'https://www.wlc.edu/esports/',TRUE),
('Wittenberg University', 'Witt_Esports', 'Springfield, OH', NULL,TRUE),
('Western Nebraska Community College', 'WNCC Esports', 'Scottsbluff, NE', 'https://www.wncc.edu/esports/',TRUE),
('Warner Pacific University', 'WPU Esports', 'Portland, OR', NULL,TRUE),
('West Texas A&M University', 'WTAMU Esports', 'Canyon, TX', 'https://www.wtamu.edu/esports/',TRUE),
('West Virginia University', 'WVU Esports', 'Morgantown, WV', 'https://www.wvu.edu/esports/',TRUE),
('Deffiance College', 'Yellowjackets', 'Defiance, OH', NULL,TRUE),
('York University', 'York University - Esports', 'York, Nebraska', NULL,TRUE);)
